name: Biodiversiteit Gulp
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Log'
  push:
    branches: [ dev ]
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v20
        with:
          files: |
            themes/custom/biodiv/scss/**/*.scss
          files_ignore: |
            *.yml

      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.changed-files-specific.outputs.any_changed == 'true'

        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: installs node modules and runs styles and js
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd themes/custom/biodiv
          npm install
          gulp styles
          gulp js

      - name: 'Upload css artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: css files
          path: themes/custom/biodiv/css


  remote_commands:
    name: execute remote commands
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            rm -rf /data/sites/web/voorvertoningbe/subsites/biodiversiteit.voorvertoning.be/modules/custom
            rm -rf /data/sites/web/voorvertoningbe/subsites/biodiversiteit.voorvertoning.be/themes/custom

  deploy:
    name: Deploy files
    runs-on: ubuntu-latest
    needs: remote_commands
    steps:
      - uses: actions/checkout@v1
      - name: Download a css artifacts
        uses: actions/download-artifact@v3
        with:
          name: css files
          path: themes/custom/biodiv/css
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm dependencies
        run: npm install
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/themes/custom/biodiv/node_modules/"
